### ISSUE TITLE
Add support for GitHub Actions

### ISSUE THREAD

**Issue by nicholaschiang** [percy/percy-js#264]
Right now, there doesn't [seem to be support](https://github.com/percy/percy-js/blob/728244da6815dbdb365ae1c44eebd01fa37d1d8a/src/environment.js#L248-L273) for GitHub Actions without having to configure things ourselves.

Right now, [this is my current configuration](https://github.com/tutorbookapp/tutorbook/blob/develop/.github/workflows/tests.yml#L9-L10) (might be helpful when creating built-in support):

```yaml
env:
  NODE_ENV: test
  PERCY_PARALLEL_NONCE: ${{ github.run_id }}
  PERCY_PARALLEL_TOTAL: 10
```
